### ISSUE TITLE
Could not resolve host: github.com

### ISSUE THREAD

**Issue by Inf-Sub** [ADmin-TkYD/SLS-Kassa.ini-Settings-Client#31]
INFO	Command: cmd.exe /c  cd "C:\...\SLS-Kassa.ini-Settings-Client" &&  git pull; Decode: cp866; View: False
INFO	Command Result: {'StdOut': '', 'StdErr': "fatal: unable to access 'https://github.com/...': **Could not resolve host: github.com**", 'ExitCode': **1}**
ERROR	Command Result Error:
{'StdOut': '', 'StdErr': "fatal: unable to access 'https://github.com/...': **Could not resolve host: github.com**", 'ExitCode': 1}
INFO	Update status: {'StdOut': '', 'StdErr': "fatal: unable to access 'https://github.com/...': **Could not resolve host: github.com**", 'ExitCode': 1}
INFO	...
ERROR	**ConnectTimeout**

**Comment by ADmin-TkYD** [comment]
added check
