### ISSUE TITLE
Параметры не применены если программа уже была запущена

### ISSUE THREAD

**Issue by Inf-Sub** [ADmin-TkYD/SLS-Kassa.ini-Settings-Client#34]
Так как ini читается в момент запуска программы, то отработка скрипта не влияет на работу программы и в результате программа перезапишет новые параметры при закрытии.
Необходимо завершать запущенный процесс программы, если она уже была запущена пользователем.

**Comment by ADmin-TkYD** [comment]
Will be implemented later

**Comment by ADmin-TkYD** [comment]
#### version 1.5.36

Added termination of the cash register program process if it is already running.

Minor fixes.

---
Добавлено завершение процесса кассовой программы, если она уже запущена.

Мелкие исправления.
