### ISSUE TITLE
Проблема с кодировкой русского текста при передаче параметров

### ISSUE THREAD

**Issue by Inf-Sub** [ADmin-TkYD/SLS-Kassa.ini-Settings-Client#35]
Русский текст в json передается в виде вопросительных знаков.

**Comment by ADmin-TkYD** [comment]
#### version 1.5.35

Generating json on the server side: Fixed a bug with json encoding (```$conn->set_charset("utf8");```). 
It is necessary to change the encoding of the entire database from latin1 to utf8.
